# This is a basic workflow to help you get started with Actions

name: Newman Run  #nome dado

# Controls when the workflow will run
on:      #onde vamos trabalhar
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:      #subir um arquivo
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  newman:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      # Roda um comando usando certos critérios
      - name: Create dir for report
        run: |
          mkdir testArtifacts

      # Runs a set of commands using the runners shell
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run test
        run:
          newman run ServeRest.postman_collection.json -e serveRest_env.postman_environment.json -r cli,htmlextra

      #vamos fazer um report usando a configuração do uses e fazemos em conjunto com o reports que estará dentro da pasta "newman"
      - name: Report
        uses: actions/upload-artifact@v4
        with: 
          name: Report
          path: newman
